name: dotnet package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
        arch: [ 'win-x64', 'win-x86', 'win-arm64' ]

    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /property:Version="$GIT_TAG_NAME"
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.arch }} --no-build --self-contained true -o "release-${{ matrix.arch }}"
      - name: Package
        run: 7z a -tzip "release-$GIT_TAG_NAME-${{ matrix.arch }}.zip" "./release-${{ matrix.arch }}/*"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "release-*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
